name: AncientEyeSMP
version: 1.0
author: NotEasyOk

settings:
  prefix: "§8[§dAncientEye§8] §f"
  xp-per-kill: 10
  max-level: 3

eyes:
  VOID:
    cooldown-primary: 10
    cooldown-secondary: 15
  STORM:
    cooldown-primary: 8
    cooldown-secondary: 20
  METEOR:
    cooldown-primary: 30
    cooldown-secondary: 60
  FLAME:
    cooldown-primary: 12
    cooldown-secondary: 25
  OCEAN:
    cooldown-primary: 15
    cooldown-secondary: 25

event-settings:
  tasks:
    - "Kill 1 Player"
    - "Break 10 Diamonds"
    - "Survive 2 Minutes"
    - "Kill 20 Zombies"
    - "Fish 5 Items"
    - "Break 64 Iron Ore"
    - "Craft 1 Golden Apple"

messages:
  no-permission: "§cNo permission!"
  cooldown-msg: "§cWait {time}s!"
  trade-success: "§aTrade successful!"
  event-start: "§6§lEVENT: §e§l{type}"
  task-complete: "§aTASK DONE! Next: {task}"
