name: AncientEyeSMP
version: 1.0
main: com.ancienteye.AncientEyePlugin
api-version: '1.21'
author: NotEasyOk
description: Unique Eye abilities and trading system.

commands:
  smpstart:
    description: Start random Eye journey.
  eye:
    description: Main command for GUI and Admin.
    aliases: [e]
  trade:
    description: Send trade request.
  tradeaccept:
    description: Accept pending trade.
  tradereject:
    description: Reject pending trade.
  event:
    description: Manage Eye events.
    permission: eye.admin

permissions:
  eye.admin:
    description: Access to all admin features.
    default: op
